[package]
name = "rysafe"
version = "0.1.0"
edition = "2021"

[lib]
name = "_rysafe_core"
crate-type = ["cdylib"]
path = "src/core/lib.rs"

[dependencies]
pyo3 = "0.25.1"

[features]
default = ["pyo3/extension-module"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true